on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - run: |
          az acr login --name mlnative
      - name: Check Docker Manifest
        id: check_manifest
        run: |
          if docker manifest inspect mlnative.azurecr.io/models/${{inputs.context}}:${{inputs.tag}} &> /dev/null; then
            echo "Docker manifest exists. Skipping build and push."
            echo "::set-output name=manifest_exists::true"
          else
            echo "Docker manifest does not exist. Proceeding with build and push."
            echo "::set-output name=manifest_exists::false"
          fi
      - name: Build and push
        if: steps.check_manifest.outputs.manifest_exists == 'false'
        uses: docker/build-push-action@v2
        with:
          context: ${{inputs.context}}
          push: true
          tags: mlnative.azurecr.io/models/${{inputs.context}}:${{inputs.tag}}